version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: python-bv
    container_name: backend
    restart: unless-stopped
    ports:
      - '8090:5000'
    volumes:
      - ./backend:/backend
    networks:
      - BV-networks

  linebot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: go-linebot
    container_name: go-linebot
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      TZ: Asia/Taipei
    volumes:
      - ./:/linebot
    networks:
      - BV-networks
    
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    networks:
      - BV-networks

  whisper-asr-webservice:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper-api
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    ports:
      - "9000:9000"
    networks:
      - BV-networks

networks:
  BV-networks:
    driver: bridge